Add LibraryViewModelTests
pastre/LearningJourney pull request #18
Opened 2021-10-06 17:39 UTC by wacumov

This PR adds unit tests for `LibraryViewModel`.
It fixes #2.

2021-10-06 20:25 UTC, pastre requested changes
Thanks for this contribution, but there are some scenarios that also need to be handled:
1. When it is already loading it should not change
2. When it fails it should update strands to proper value

Also, you need to test `handleUserDidChange` and `handleSignout`

2021-10-06 20:25 UTC, pastre commented on LearningJourney/Modules/Features/JLibrary/JLibraryTests/Sources/Scenes/Library/Library/LibraryViewModelTests.swift
> +final class SignoutUseCaseStub: SignoutUseCaseProtocol {
This is actually a dummy, since it doesn't play a role in the tests

2021-10-06 20:25 UTC, pastre commented on LearningJourney/Modules/Features/JLibrary/JLibraryTests/Sources/Scenes/Library/Library/LibraryViewModelTests.swift
> +final class FetchStrandsUseCaseMock: FetchStrandsUseCaseProtocol {
This is stub, since it provides canned answers for expected test scenarios

2021-10-07 19:56 UTC, wacumov commented on LearningJourney/Modules/Features/JLibrary/JLibraryTests/Sources/Scenes/Library/Library/LibraryViewModelTests.swift
> +final class SignoutUseCaseStub: SignoutUseCaseProtocol {
I renamed these test helpers according to your recommendations, but then I've added more test cases and these helpers became more complex, so I renamed them to mocks.

2021-10-08 14:48 UTC, pastre requested changes
Great job overall! xD

2021-10-08 14:48 UTC, pastre commented on LearningJourney/Modules/Features/JLibrary/JLibraryTests/Sources/Scenes/Library/Library/LibraryViewModelTests.swift
> +        XCTAssertEqual(sut.strands, .loading)
A better way to test this is to assert `useCases.fetchStrandsUseCase.execute` is called only once, since the function itself sets to `.loading` and, if the test would fail, it would still be calling `useCases.fetchStrandsUseCase.execute` twice. Consider making a spy on `useCases.fetchStrandsUseCase.execute` and asserting it is being called only once

2021-10-08 14:49 UTC, pastre commented on LearningJourney/Modules/Features/JLibrary/JLibraryTests/Sources/Scenes/Library/Library/LibraryViewModelTests.swift
> +final class SignoutUseCaseStub: SignoutUseCaseProtocol {
Makes sense :)

2021-10-09 08:20 UTC, wacumov commented on LearningJourney/Modules/Features/JLibrary/JLibraryTests/Sources/Scenes/Library/Library/LibraryViewModelTests.swift
> +        XCTAssertEqual(sut.strands, .loading)
Thanks for the suggestion, I hope I understand correctly what you mean.

2021-10-09 15:17 UTC, pastre commented on LearningJourney/Modules/Features/JLibrary/JLibraryTests/Sources/Scenes/Library/Library/LibraryViewModelTests.swift
> +        XCTAssertEqual(sut.strands, .loading)
@wacumov  That's almost it! Now we can remove `shouldHandle ` from our spy, since we've tested that the function will only be called once :)

2021-10-10 07:22 UTC, wacumov commented on LearningJourney/Modules/Features/JLibrary/JLibraryTests/Sources/Scenes/Library/Library/LibraryViewModelTests.swift
> +        XCTAssertEqual(sut.strands, .loading)
@pastre Removing `shouldHandle` from `FetchStrandsUseCaseMock` leads to the test case failure: the mock returns result immediately so at the moment of the second `handleOnAppear` call the `sut` has already in `.result` state (not `.loading`).
We can remove `shouldHandle`, but it requires to add a delay to `FetchStrandsUseCaseMock.execute` method. I think that to keep `shouldHandle` is better solution than to adding a delay. What do you think?

2021-10-10 18:37 UTC, pastre commented on LearningJourney/Modules/Features/JLibrary/JLibraryTests/Sources/Scenes/Library/Library/LibraryViewModelTests.swift
> +        XCTAssertEqual(sut.strands, .loading)
It makes sense! Lets keep `shouldHandle` then

2021-10-10 18:38 UTC, pastre approved these changes

2021-10-10 18:43 UTC, merged