Objectives List ViewModel unit tests
pastre/LearningJourney pull request #22
Opened 2021-10-09 13:08 UTC by azolinmf

## Description
This PR fixes issue #7, adding unit tests to `ObjectivesListViewModel`.

## Testing Plan 

Run project unit tests.

2021-10-09 15:32 UTC, pastre requested changes

2021-10-09 15:32 UTC, pastre commented on LearningJourney/Modules/Core/TestingUtils/TestingUtils/Sources/Spies/FetchObjectivesUseCaseSpy.swift
> +
You can remove this header, its just increasing LOC count

2021-10-09 15:32 UTC, pastre commented on LearningJourney/Modules/Core/TestingUtils/TestingUtils/Sources/Spies/FetchObjectivesUseCaseSpy.swift
> +public final class FetchObjectivesUseCaseSpy: FetchObjectivesUseCaseProtocol {
This shouldn't be in `TestingUtils`, because now `TestingUtils` depends on JLibrary. We should invert that dependency and add our doubles only to the module we're testing. That also means that every dependency of `TestingUtils` will needlesly compile this double. Also, none of these need to be public

TestingUtils is meant for generic implementations only :)

2021-10-09 15:32 UTC, pastre commented on LearningJourney/Modules/Core/TestingUtils/TestingUtils/Sources/Spies/FetchObjectivesUseCaseSpy.swift
> +import Foundation
I don't think you need to import `Foundation` here since `Result` is a Swift feature

2021-10-09 15:32 UTC, pastre commented on LearningJourney/Modules/Core/TestingUtils/TestingUtils/Sources/Spies/ToggleLearnUseCaseSpy.swift
> +public final class ToggleLearnUseCaseSpy: ToggleLearnUseCaseProtocol {
Same as above

2021-10-09 15:32 UTC, pastre commented on LearningJourney/Modules/Features/JLibrary/JLibraryTests/Sources/Scenes/ObjectivesLisst/Domain/ObjectivesListViewModelTests.swift
> +
```suggestion
    // MARK: - Properties
```

2021-10-09 15:32 UTC, pastre commented on LearningJourney/Modules/Features/JLibrary/JLibraryTests/Sources/Scenes/ObjectivesLisst/Domain/ObjectivesListViewModelTests.swift
> +        let learningGoal = LearningGoal.init(id: 1, name: "goal", progress: 0)
Consider renaming this to better match it's role in the test
Also, create a fixture :)
```suggestion
        let expectedLearningGoal = LearningGoal.init(id: 1, name: "goal", progress: 0)
```

2021-10-09 15:32 UTC, pastre commented on LearningJourney/Modules/Features/JLibrary/JLibraryTests/Sources/Scenes/ObjectivesLisst/Domain/ObjectivesListViewModelTests.swift
> +        fetchObjectivesUseCaseSpy.shouldHandle = false
This should not be necessary, since the function should return before the use case is executed. Asserting `executeCallCount == 1` is good enough

2021-10-09 15:32 UTC, pastre commented on LearningJourney/Modules/Features/JLibrary/JLibraryTests/Sources/Scenes/ObjectivesLisst/Domain/ObjectivesListViewModelTests.swift
> +        sut.handleOnAppear()
This should be a `given`, since it prepares the sut

2021-10-09 15:32 UTC, pastre commented on LearningJourney/Modules/Features/JLibrary/JLibraryTests/Sources/Scenes/ObjectivesLisst/Domain/ObjectivesListViewModelTests.swift
> +    }
Consider creating a `fixture` for this. It makes it way easier to instantiate objects in our tests, since we can just use `.fixture()` and modify the parameters we need modified
```suggestion
extension LearningObjective {
	  static func fixture(
	  	id: Int = .init(),
	  	code: String = .init(),
	  	description: String = .init(),
	  	isCore: Bool = .random(),
	  	isComplete: Bool = .random()
	  ) -> LearningObjective  {
		    LearningObjective(
			      id: id,
			      code: "code",
			      description: "description",
			      isCore: Bool.random(),
			      isComplete: Bool.random()
		
		)
	  }
}
```

2021-10-09 15:32 UTC, pastre commented on LearningJourney/Modules/Features/JLibrary/JLibraryTests/Sources/Scenes/ObjectivesLisst/Domain/ObjectivesListViewModelTests.swift
> +        let firstLearningObjective = createLearningObjective(id: 1)
This is a dummy, since it only exists to build the scenerio

2021-10-09 15:32 UTC, pastre commented on LearningJourney/Modules/Features/JLibrary/JLibraryTests/Sources/Scenes/ObjectivesLisst/Domain/ObjectivesListViewModelTests.swift
> +        let secondLearningObjective = createLearningObjective(id: 2)
This is a stub, since you inject it in the test with a canned answer to build a scenario

2021-10-10 18:40 UTC, pastre requested changes

2021-10-10 18:40 UTC, pastre commented on LearningJourney/Modules/Features/JLibrary/JLibraryTests/Sources/TestUtils/FetchObjectivesUseCaseSpy.swift
> +    init() {}
```suggestion
```

2021-10-10 18:40 UTC, pastre commented on LearningJourney/Modules/Features/JLibrary/JLibraryTests/Sources/TestUtils/FetchObjectivesUseCaseSpy.swift
> +final class FetchObjectivesUseCaseSpy: FetchObjectivesUseCaseProtocol {
```suggestion
final class FetchObjectivesUseCaseSpyStub: FetchObjectivesUseCaseProtocol {
```

2021-10-10 18:40 UTC, pastre commented on LearningJourney/Modules/Features/JLibrary/JLibraryTests/Sources/TestUtils/ToggleLearnUseCaseSpy.swift
> +    init() {}
```suggestion
```

2021-10-10 18:40 UTC, pastre commented on LearningJourney/Modules/Features/JLibrary/JLibraryTests/Sources/TestUtils/ToggleLearnUseCaseSpy.swift
> +final class ToggleLearnUseCaseSpy: ToggleLearnUseCaseProtocol {
```suggestion
final class ToggleLearnUseCaseSpyStub: ToggleLearnUseCaseProtocol {
```

2021-10-10 19:23 UTC, azolinmf commented on LearningJourney/Modules/Features/JLibrary/JLibraryTests/Sources/TestUtils/FetchObjectivesUseCaseSpy.swift
> +final class FetchObjectivesUseCaseSpy: FetchObjectivesUseCaseProtocol {
[done](https://github.com/pastre/LearningJourney/pull/22/commits/1b688e06d18398880e670979fd069ea846de1158) :)

2021-10-11 02:53 UTC, pastre approved these changes
dalhe ❤️

2021-10-11 11:13 UTC, merged