Creates FetchObjectivesUseCaseTests
pastre/LearningJourney pull request #23
Opened 2021-10-10 17:35 UTC by vcoutasso

## Description
Adds unit tests to `FetchObjectivesUseCase`

## Why?
Resolves #8

2021-10-10 18:42 UTC, pastre requested changes

2021-10-10 18:42 UTC, pastre commented on LearningJourney/Modules/Features/JLibrary/JLibraryTests/Sources/Scenes/ObjectivesLisst/Domain/UseCases/FetchObjectivesUseCaseTests.swift
> +fileprivate final class LibraryRepositorySpy: LibraryRepositoryProtocol  {
Its ok to share doubles in tests, this can be internal
```suggestion 
final class LibraryRepositorySpy: LibraryRepositoryProtocol  {
```

2021-10-10 18:42 UTC, pastre commented on LearningJourney/Modules/Features/JLibrary/JLibraryTests/Sources/Scenes/ObjectivesLisst/Domain/UseCases/ToggleLearnUseCaseTests.swift
> +private final class LibraryRepositorySpy: LibraryRepositoryProtocol  {
```suggestion
final class LibraryRepositorySpy: LibraryRepositoryProtocol  {
```

2021-10-10 19:08 UTC, pastre approved these changes

2021-10-10 19:15 UTC, vcoutasso commented on LearningJourney/Modules/Features/JLibrary/JLibraryTests/Sources/Scenes/ObjectivesLisst/Domain/UseCases/ToggleLearnUseCaseTests.swift
> +private final class LibraryRepositorySpy: LibraryRepositoryProtocol  {
I  didn't notice that applying these suggestions without any further adjustments would resurface the exact issue I was trying to solve by making those `fileprivate`: it makes it so that one of them would be an invalid redeclaration since the names are the same. I suppose I could either change their names to match the sut, extract this declaration to a separate file and implement everything that I need there or just keep them private. Any suggestions?

2021-10-11 02:56 UTC, pastre commented on LearningJourney/Modules/Features/JLibrary/JLibraryTests/Sources/Scenes/ObjectivesLisst/Domain/UseCases/ToggleLearnUseCaseTests.swift
> +private final class LibraryRepositorySpy: LibraryRepositoryProtocol  {
Can't you just implement the functions on one spy? I mean, you have two classes that implement a protocol, and each of them throw an error on a different function. Just remove `fatalError` from one of them and delete one spy :)

2021-10-11 15:58 UTC, vcoutasso commented on LearningJourney/Modules/Features/JLibrary/JLibraryTests/Sources/Scenes/ObjectivesLisst/Domain/UseCases/ToggleLearnUseCaseTests.swift
> +private final class LibraryRepositorySpy: LibraryRepositoryProtocol  {
Of course! Will do 🚀

2021-10-11 16:13 UTC, merged